# Generated by Django 3.1.12 on 2021-06-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_id', models.CharField(max_length=50)),
                ('twitch_login', models.CharField(max_length=50)),
                ('twitch_name', models.CharField(max_length=50)),
            ],
        ),
    ]
