# Generated by Django 3.1.12 on 2021-07-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0004_channelfollow_gamefollow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelfollow',
            old_name='follower',
            new_name='followed',
        ),
        migrations.RenameField(
            model_name='gamefollow',
            old_name='follower',
            new_name='followed',
        ),
    ]
