# Generated by Django 3.1.12 on 2021-08-22 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('clips', '0005_auto_20210714_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip_twitch_id', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField()),
                ('embed_url', models.URLField()),
                ('broadcaster_id', models.CharField(max_length=50)),
                ('broadcaster_name', models.CharField(max_length=250)),
                ('creator_id', models.CharField(max_length=50)),
                ('creator_name', models.CharField(max_length=250)),
                ('video_id', models.CharField(max_length=50)),
                ('twitch_game_id', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('twitch_view_count', models.CharField(max_length=15)),
                ('glip_view_count', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField()),
                ('thumbnail_url', models.URLField()),
                ('duration', models.CharField(max_length=10)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
        migrations.RemoveField(
            model_name='gamefollow',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='gamefollow',
            name='following',
        ),
        migrations.DeleteModel(
            name='ChannelFollow',
        ),
        migrations.DeleteModel(
            name='Channels',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GameFollow',
        ),
    ]
