# Generated by Django 3.1.12 on 2021-09-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0006_auto_20210822_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='twitch_view_count',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
