# Generated by Django 3.1.12 on 2021-09-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0007_auto_20210901_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='id',
        ),
        migrations.AlterField(
            model_name='clip',
            name='clip_twitch_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
