# Generated by Django 3.1.12 on 2021-10-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0009_auto_20211013_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
