# Generated by Django 3.1.12 on 2021-10-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0010_clip_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='created_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='clip',
            name='disabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='clip',
            name='glip_view_count',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
    ]
