# Generated by Django 3.1.12 on 2021-10-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0011_auto_20211031_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='glip_view_count',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clip',
            name='twitch_view_count',
            field=models.DecimalField(db_index=True, decimal_places=0, max_digits=10),
        ),
    ]
