# Generated by Django 3.1.12 on 2021-11-08 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0012_auto_20211031_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopClip',
            fields=[
                ('clip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clips.clip')),
            ],
        ),
    ]
