# Generated by Django 3.1.12 on 2021-09-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_queried_clips',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
