# Generated by Django 3.1.12 on 2021-09-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_last_tried_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopGame',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('box_art_url', models.TextField()),
            ],
        ),
    ]
