# Generated by Django 3.1.12 on 2021-09-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_topgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='topgame',
            name='order',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
