# Generated by Django 3.1.12 on 2021-11-13 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0006_auto_20211021_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='follows',
            field=models.ManyToManyField(blank=True, default=None, related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
