# Generated by Django 3.1.12 on 2021-06-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channels',
            field=models.ManyToManyField(to='clips.Channels'),
        ),
    ]
