# Generated by Django 3.1.12 on 2021-07-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_channels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='channels',
        ),
    ]
